[package]
name = "rsign2"
version = "0.5.6"
authors = ["Frank Denis <github@pureftpd.org>", "Daniel Rangel <daniel@rangel.in>"]
description = "A command-line tool to sign files and verify signatures."
edition = "2018"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "cryptography"]
keywords = ["command-line", "sign", "publickey", "cryptography", "minisign"]
repository = "https://github.com/jedisct1/rsign2"

[dependencies]
clap = "2.33.1"
minisign = "0.5.16"

[target.'cfg(any(windows, unix))'.dependencies]
dirs-next = "1.0.0"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
